version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094

  topic-creator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka1
    entrypoint: |
      bash -c "
      /usr/bin/kafka-topics --create --topic meu_topico --bootstrap-server kafka1:9092 --partitions 3 --replication-factor 2 &&
      /usr/bin/kafka-topics --create --topic topicos_processados --bootstrap-server kafka1:9092 --partitions 3 --replication-factor 2"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  python-app:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: python-app
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
